#!/usr/bin/env node
// The app icon is complete and comes from one run of its own generator.
//
// Two ways the icon has already gone wrong and this check refuses:
//
//  1. `crates/sta/res/sta.ico` shipped with a *single* 32x32 entry. Windows then has nothing to do
//     but upscale 32 px for Explorer's Large (48) / Extra Large (96) / tile (256) views, the Start
//     menu, jump lists, pinned shortcuts and Alt+Tab at 150 % DPI — every one of them blurry.
//  2. `res/make_icon.py` was edited and never re-run, so the committed artwork (a black starburst)
//     and the generator's artwork (the purple atom that `ui/empty/empty.js` and Settings > About
//     draw) were two different pictures, and build.rs's own "make_icon.py regenerates the icon"
//     would have silently rebranded the application.
//
// Rule 2 is enforced by provenance rather than by re-rendering: `make_icon.py` writes the ICO and
// the four runtime PNGs from one master image in one pass, and Pillow stores every ICO entry as a
// PNG blob, so `sta.ico`'s 16/32/48/64 entries are byte-identical to `icon-16/32/48/64.png` exactly
// when both came from the same run. Regenerate with:
//
//   python crates/sta/res/make_icon.py crates/sta/res
//
//   node tools/check-icon.mjs        exit 0 = clean, 1 = problems

import { readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(join(dirname(fileURLToPath(import.meta.url)), '..'));
const res = join(root, 'crates', 'sta', 'res');
/** Sizes Windows asks for that must be drawn, not upscaled. */
const REQUIRED = [16, 32, 48, 256];
/** The PNGs `crates/sta/src/window.rs` embeds for the runtime window icon. */
const RUNTIME = [16, 32, 48, 64];
const PNG_MAGIC = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

const problems = [];
const fail = (message) => problems.push(message);

const ico = readFileSync(join(res, 'sta.ico'));
if (ico.readUInt16LE(0) !== 0 || ico.readUInt16LE(2) !== 1) fail('res/sta.ico is not an icon file (reserved/type header)');
const count = ico.readUInt16LE(4);
/** @type {Map<number, Buffer>} */
const entries = new Map();
for (let i = 0; i < count; i++) {
  const at = 6 + i * 16;
  const w = ico[at] || 256;
  const h = ico[at + 1] || 256;
  const bpp = ico.readUInt16LE(at + 6);
  const size = ico.readUInt32LE(at + 8);
  const offset = ico.readUInt32LE(at + 12);
  if (w !== h) fail(`res/sta.ico entry ${i} is ${w}x${h}, not square`);
  if (bpp !== 32) fail(`res/sta.ico entry ${w}x${h} is ${bpp} bpp, not 32 (no alpha)`);
  if (offset + size > ico.length) fail(`res/sta.ico entry ${w}x${h} runs past the end of the file`);
  entries.set(w, ico.subarray(offset, offset + size));
}
for (const size of REQUIRED) {
  if (!entries.has(size)) fail(`res/sta.ico has no ${size}x${size} entry (Windows would upscale; it has ${[...entries.keys()].sort((a, b) => a - b).join(', ')})`);
}

/** A PNG blob's IHDR dimensions, or null when it is not a PNG. */
function pngSize(buf) {
  if (buf.length < 24 || !buf.subarray(0, 8).equals(PNG_MAGIC)) return null;
  return [buf.readUInt32BE(16), buf.readUInt32BE(20)];
}

for (const size of RUNTIME) {
  const file = `icon-${size}.png`;
  const png = readFileSync(join(res, file));
  const dims = pngSize(png);
  if (!dims) {
    fail(`res/${file} is not a PNG`);
    continue;
  }
  if (dims[0] !== size || dims[1] !== size) fail(`res/${file} is ${dims[0]}x${dims[1]}, not ${size}x${size}`);
  const inIco = entries.get(size);
  if (!inIco) continue; // already reported above when required
  if (!inIco.equals(png)) {
    fail(`res/${file} and res/sta.ico's ${size}x${size} entry differ: the two were generated by different runs of res/make_icon.py — re-run "python crates/sta/res/make_icon.py crates/sta/res" and commit all of them together`);
  }
}

for (const [size, blob] of entries) {
  const dims = pngSize(blob);
  if (dims && (dims[0] !== size || dims[1] !== size)) fail(`res/sta.ico entry declared ${size}x${size} holds a ${dims[0]}x${dims[1]} image`);
}

if (problems.length) {
  for (const p of problems) console.log(`FAIL ${p}`);
  console.log(`\ncheck-icon: ${problems.length} problem(s)`);
  process.exit(1);
}
console.log(`check-icon: res/sta.ico has ${count} sizes (${[...entries.keys()].sort((a, b) => a - b).join(', ')}) and the ${RUNTIME.length} runtime PNGs are the same render`);
